### ISSUE TITLE
PCPCの旋回重心軌道が予見制御の重心軌道とズレている

### ISSUE THREAD

**Issue by Akira794** [open-rdc/PCPC#2]
一歩分の重心軌道を接続していくことでPCPC(係数のみ)による45deg旋回はできたが、予見制御で作成した重心軌道と比べ軌道がずれている.
![check_diff](https://user-images.githubusercontent.com/7345211/69202614-8e0d1780-0b85-11ea-8692-2e9b0b3792d4.png)

**Comment by Akira794** [comment]
重心速度、重心加速度の確認

重心速度
![45deg_vel_x](https://user-images.githubusercontent.com/7345211/69202842-1d1a2f80-0b86-11ea-8c10-1cd0be81c497.png)
![45deg_vel_y](https://user-images.githubusercontent.com/7345211/69202848-21dee380-0b86-11ea-83e7-10f029900d33.png)

重心加速度
![45deg_acc_x](https://user-images.githubusercontent.com/7345211/69202855-299e8800-0b86-11ea-802b-4706d39556e0.png)
![45deg_acc_y](https://user-images.githubusercontent.com/7345211/69202860-2d320f00-0b86-11ea-8532-21f1f70cddba.png)

**Comment by Akira794** [comment]
旋回時の重心速度・重心加速度
重心速度・加速度の縦軸それぞれ dx,dy, ddx, ddy 
重心速度
![45deg_vel_x](https://user-images.githubusercontent.com/7345211/69204418-33c28580-0b8a-11ea-8de1-5512132a580a.png)
![45deg_vel_y](https://user-images.githubusercontent.com/7345211/69204425-3a50fd00-0b8a-11ea-98de-4bdb926e3470.png)
重心加速度
![45deg_acc_x](https://user-images.githubusercontent.com/7345211/69204443-42a93800-0b8a-11ea-8c4b-0359e50e2120.png)
![45deg_acc_y](https://user-images.githubusercontent.com/7345211/69204449-450b9200-0b8a-11ea-953e-a0de41390861.png)

**Comment by Akira794** [comment]
・ロボットの基準座標では移動する度に重心速度は双曲線に近いが、固定座標系では移動する度にx,yが回転するため 基準座標系ではx方向に速度があっても固定座標系ではy方向に速度が出ていることになる?

**Comment by Akira794** [comment]
90degでの場合
重心速度・加速度の縦軸それぞれ dx,dy, ddx, ddy 
![90deg_rotate](https://user-images.githubusercontent.com/7345211/69206487-26a89500-0b90-11ea-8e2a-a172100b003b.png)

重心速度
![90deg_vel_x](https://user-images.githubusercontent.com/7345211/69206498-2f00d000-0b90-11ea-9bbd-fe1ce426cfaf.png)
![90deg_vel_y](https://user-images.githubusercontent.com/7345211/69206501-31632a00-0b90-11ea-930c-82011cda51a7.png)
重心加速度
![90deg_acc_x](https://user-images.githubusercontent.com/7345211/69206525-3f18af80-0b90-11ea-86b2-0317cb79c00f.png)
![90deg_acc_y](https://user-images.githubusercontent.com/7345211/69206527-4213a000-0b90-11ea-9d0a-84f30cb7d2ee.png)

**Comment by Akira794** [comment]
旋回によって速度・加速度ともに1歩毎の変化がx成分・y成分共に入れ替わっている？

**Comment by yasuohayashibara** [comment]
まずは，0deg（直進）で一致するかから行ったほうが良いかもしれません．

**Comment by Akira794** [comment]
0deg は以下のとおりです

![0deg_cog](https://user-images.githubusercontent.com/7345211/69220543-a0547900-0bb8-11ea-9c1a-ed4a408cc608.png)

重心速度
![0deg_vel_x](https://user-images.githubusercontent.com/7345211/69220571-aea29500-0bb8-11ea-9720-82d21b854873.png)
![0deg_vel_y](https://user-images.githubusercontent.com/7345211/69220576-b104ef00-0bb8-11ea-9d89-954721823471.png)

重心加速度
![0deg_acc_x](https://user-images.githubusercontent.com/7345211/69220586-b6fad000-0bb8-11ea-8a55-422a4a5871bc.png)
![0deg_acc_y](https://user-images.githubusercontent.com/7345211/69220597-bc581a80-0bb8-11ea-9467-f216acb8b4c1.png)

**Comment by yasuohayashibara** [comment]
早速ありがとう．
こちらはほぼ一致していますね．
角度を変えながら，どのようにずれていくかを観察すれば，解決できるかもしれません．

**Comment by Akira794** [comment]
各毎歩の初期重心速度に旋回角分座標変換(-9deg)したところ固定座標系での重心軌道がほぼ一致
![45deg_vel_ok](https://user-images.githubusercontent.com/7345211/69519572-b9d13880-0f9d-11ea-9ed1-ce6b1c8ef382.png)

**Comment by Akira794** [comment]
重心加速度の出力にも旋回角分の座標変換を行う

**Comment by Akira794** [comment]
重心速度・重心加速度の確認
45deg
重心速度
![45deg_vel_x](https://user-images.githubusercontent.com/7345211/69606757-092f6b80-1067-11ea-9489-46aa26233301.png)
![45deg_vel_y](https://user-images.githubusercontent.com/7345211/69606764-0c2a5c00-1067-11ea-85eb-2cd3615da33d.png)

重心加速度
![45deg_acc_x](https://user-images.githubusercontent.com/7345211/69606770-13516a00-1067-11ea-9008-2c4bbf443ca4.png)
![45deg_acc_y](https://user-images.githubusercontent.com/7345211/69606774-164c5a80-1067-11ea-966e-b71ec708bfeb.png)

**Comment by Akira794** [comment]
ズレが解消されたため閉じる
